language:
  - node_js

node_js:
  - "0.12"

env:
  CODECLIMATE_REPO_TOKEN: b74e18938d2767c9a21e918829df8adb62cdaf2f13b0a910137dbb8aceb9cbed

before_script:
- npm install -g codeclimate-test-reporter

after_success:
  - codeclimate < ./coverage/lcov.info
